---
docker_prerequisites:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
docker_gpg_url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
docker_repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
docker_package: docker-ce
docker_group: docker